export {
  DEFAULT_JSON_DECODE_OPTIONS,
  DEFAULT_JSON_SCHEMA_PARSE_OPTIONS,
  DEFAULT_JSON_SCHEMA_PARSE_OPTIONS as DEFAULT_JSON_PARSE_OPTIONS,
  assertSupportedJsonSchemaParseOptions,
  assertSupportedJsonSchemaParseOptions as assertSupportedJsonParseOptions,
  configureJsonSchemaParser,
  configureJsonSchemaParser as configureJsonParser,
  createJsonSchemaParser,
  createJsonSchemaParser as createJsonParser,
  prepareJsonSchemaParseOptions,
  prepareJsonSchemaParseOptions as prepareJsonParseOptions,
  resolveJsonDecodeOptions,
  resolveJsonSchemaParseOptions,
  resolveJsonSchemaParseOptions as resolveJsonParseOptions,
  validateJsonDecodeOptions,
  validateJsonSchemaParseOptions,
  validateJsonSchemaParseOptions as validateJsonParseOptions,
} from "./schema/options.js";

export type {
  JsonDecodeOptions,
  JsonDiagnosticsOptions,
  JsonEmptyArrayMode,
  JsonMixedTypeMode,
  JsonNullHandling,
  JsonNumericMode,
  JsonParseStrictness,
  JsonRecordInferenceMode,
  JsonSchemaInferenceOptions,
  JsonSchemaInferenceOptions as JsonInferenceOptions,
  JsonSchemaParseOptions,
  JsonSchemaParseOptions as JsonParseOptions,
  JsonTupleInferenceMode,
  ResolvedJsonDecodeOptions,
  ResolvedJsonSchemaParseOptions,
  ResolvedJsonSchemaParseOptions as ResolvedJsonParseOptions,
} from "./schema/options.js";
