export type {
  SchemaArrayNode as ShapeArrayNode,
  SchemaBaseNode as ShapeBaseNode,
  SchemaDefinition as ShapeDefinition,
  SchemaDocument as ShapeDocument,
  SchemaFieldNode as ShapeFieldNode,
  SchemaLiteralNode as ShapeLiteralNode,
  SchemaNode as ShapeNode,
  SchemaNodeKind as ShapeNodeKind,
  SchemaNullNode as ShapeNullNode,
  SchemaObjectNode as ShapeObjectNode,
  SchemaReferenceNode as ShapeReferenceNode,
  SchemaRecordNode as ShapeRecordNode,
  SchemaScalarNode as ShapeScalarNode,
  SchemaTupleElement as ShapeTupleElement,
  SchemaTupleNode as ShapeTupleNode,
  SchemaUnionNode as ShapeUnionNode,
  SchemaUnknownNode as ShapeUnknownNode,
} from "../schema/types.js";

export type {
  SchemaDefinitionIndex as ShapeDefinitionIndex,
  SchemaReferenceResolution as ShapeReferenceResolution,
} from "../schema/definitions.js";

export type {
  SchemaPath as ShapePath,
  SchemaPathSegment as ShapePathSegment,
} from "../schema/path.js";

export type {
  SchemaTransformContext as ShapeTransformContext,
  SchemaTransformReachabilityMode as ShapeTransformReachabilityMode,
  SchemaTransformOptions as ShapeTransformOptions,
  SchemaTransformReferenceMode as ShapeTransformReferenceMode,
  SchemaTransformer as ShapeTransformer,
} from "../schema/transform.js";

export type {
  SchemaWalkContext as ShapeWalkContext,
  SchemaWalkNodeContext as ShapeWalkNodeContext,
  SchemaWalkOptions as ShapeWalkOptions,
  SchemaReferenceTraversalStatus as ShapeReferenceTraversalStatus,
  SchemaWalkReferenceMode as ShapeWalkReferenceMode,
  SchemaWalkVia as ShapeWalkVia,
  SchemaWalkVisitor as ShapeWalkVisitor,
} from "../schema/traversal.js";

export type {
  IdentifierName,
  ScalarKind,
  SchemaArrayNode,
  SchemaBaseNode,
  SchemaDefinition,
  SchemaDiagnostic,
  SchemaDiagnosticNodeKind,
  SchemaDiagnosticSeverity,
  SchemaDocument,
  SchemaFieldNode,
  SchemaLiteralNode,
  SchemaLiteralValue,
  SchemaNode,
  SchemaNodeKind,
  SchemaNullNode,
  SchemaObjectNode,
  SchemaReferenceNode,
  SchemaRecordNode,
  SchemaScalarNode,
  SchemaSemanticNote,
  SchemaSemanticNoteKind,
  SchemaSemanticNoteLayer,
  SchemaTupleElement,
  SchemaTupleNode,
  SchemaUnionNode,
  SchemaUnknownEvidence,
  SchemaUnknownNode,
  SchemaValidationFailureResult,
  SchemaValidationResult,
  SchemaValidationSuccessResult,
  UnknownReason,
} from "../schema/types.js";

export type {
  SchemaDefinitionIndex,
  SchemaReferenceResolution,
} from "../schema/definitions.js";

export type {
  SchemaPath,
  SchemaPathSegment,
} from "../schema/path.js";

export type {
  SchemaTransformContext,
  SchemaTransformReachabilityMode,
  SchemaTransformOptions,
  SchemaTransformReferenceMode,
  SchemaTransformer,
} from "../schema/transform.js";

export type {
  SchemaWalkContext,
  SchemaWalkNodeContext,
  SchemaWalkOptions,
  SchemaReferenceTraversalStatus,
  SchemaWalkReferenceMode,
  SchemaWalkVia,
  SchemaWalkVisitor,
} from "../schema/traversal.js";

export {
  appendSchemaPath,
  areEquivalentSchemaNodes,
  createSchemaDefinitionIndex,
  createSchemaDefinitionIndexFromLookup,
  createDefinitionSchemaPath,
  createRootSchemaPath,
  identifierName,
  resolveSchemaReference,
  isSchemaArrayNode,
  isSchemaLiteralNode,
  isSchemaNullNode,
  isSchemaObjectNode,
  isSchemaRecordNode,
  isSchemaReferenceNode,
  isSchemaScalarNode,
  isSchemaTupleNode,
  isSchemaUnionNode,
  isSchemaUnknownNode,
  schemaArrayNode,
  schemaDefinition,
  schemaDocument,
  schemaFieldNode,
  schemaLiteralNode,
  schemaNullNode,
  schemaObjectNode,
  schemaRecordNode,
  schemaReferenceNode,
  schemaPathSegmentToDiagnosticToken,
  schemaPathToDiagnosticPath,
  schemaScalarNode,
  schemaTupleElement,
  schemaTupleNode,
  schemaUnionNode,
  schemaUnknownNode,
  normalizeSchemaDefinitions,
  normalizeSchemaDocument,
  normalizeSchemaDocumentFromRoot,
  normalizeSchemaDocumentStructure,
  normalizeSchemaNode,
  transformSchemaDocument,
  transformSchemaDocumentFromRoot,
  transformSchemaDocumentStructure,
  transformSchemaDefinitions,
  transformSchemaNode,
  walkSchemaDefinitions,
  walkSchemaDocument,
  walkSchemaDocumentFromRoot,
  walkSchemaDocumentStructure,
  walkSchemaNode,
  tryValidateSchemaDocument,
  tryValidateSchemaFieldNullability,
  validateSchemaDocument,
  validateSchemaFieldNullability,
} from "../schema/index.js";

export {
  schemaArrayNode as shapeArrayNode,
  schemaDefinition as shapeDefinition,
  schemaDocument as shapeDocument,
  schemaFieldNode as shapeFieldNode,
  schemaLiteralNode as shapeLiteralNode,
  schemaNullNode as shapeNullNode,
  schemaObjectNode as shapeObjectNode,
  schemaRecordNode as shapeRecordNode,
  schemaReferenceNode as shapeReferenceNode,
  schemaScalarNode as shapeScalarNode,
  schemaTupleElement as shapeTupleElement,
  schemaTupleNode as shapeTupleNode,
  schemaUnionNode as shapeUnionNode,
  schemaUnknownNode as shapeUnknownNode,
} from "../schema/index.js";
